#!/bin/sh

echo "=== Compare Assignment Setup ==="

# Wait for WordPress core files (written by the wordpress container).
echo "Waiting for WordPress files..."
until [ -f /var/www/html/wp-includes/version.php ]; do
    sleep 3
done
echo "WordPress files found."

# Wait for wp-config.php (generated by the wordpress container from env vars).
echo "Waiting for wp-config.php..."
until [ -f /var/www/html/wp-config.php ]; do
    sleep 2
done
echo "wp-config.php found."

# Wait for the database by retrying wp core install directly.
# This uses PHP's mysqli (not the mariadb CLI), avoiding TLS client issues.
echo "Waiting for database and installing WordPress..."
retries=0
until wp core is-installed 2>/dev/null; do
    retries=$((retries + 1))
    if [ $retries -ge 30 ]; then
        echo "ERROR: Could not connect to database after 60 seconds."
        exit 1
    fi

    # Attempt install on each retry — it will fail gracefully if DB isn't ready yet.
    wp core install \
        --url="http://localhost:8080" \
        --title="Compare Assignment" \
        --admin_user=admin \
        --admin_password=admin \
        --admin_email=admin@example.com \
        --skip-email 2>/dev/null

    sleep 2
done
echo "WordPress installed."

# Set pretty permalinks so /compare-assignment/ works as a clean URL.
wp rewrite structure '/%postname%/'
wp rewrite flush

# Activate the plugin (triggers the activation hook which creates the page).
echo "Activating Compare Assignment plugin..."
wp plugin activate compare-assignment

echo ""
echo "============================================"
echo "  Setup complete!"
echo "  Visit: http://localhost:8080/compare-assignment/"
echo "  Admin: http://localhost:8080/wp-admin/"
echo "  Login: admin / admin"
echo "============================================"